// Code generated by json2struct 1.5. (@generated) DO NOT EDIT.
// cmdline: `json2struct -out=mySettings.go -declare=mySettings -pkg=main -raw= default-settings.jsonc`

package main

type MySettings struct {
	Main	MySettings_Main	`json:"Main"`
	Users	[]MySettings_UsersItem	`json:"Users"`
}

type MySettings_Main struct {
	ParamString	string	`json:"ParamString"`
	ParamBool	bool	`json:"ParamBool"`
	ParamInt	int	`json:"ParamInt"`
	ParamFloat	float64	`json:"ParamFloat"`
}

type MySettings_UsersItem struct {
	Name	string	`json:"name"`
	Email	string	`json:"email"`
}

func defaultMySettings() MySettings {
	return MySettings{

		Main: MySettings_Main{
			ParamString: "ParamValue \n \"test\"",
			ParamBool: true,
			ParamInt: 12,
			ParamFloat: 1.234,
		},
		Users: []MySettings_UsersItem{
			{
				Name: "John",
				Email: "john@email",
			},
			{
				Name: "Smith",
			},
		},
	}
}

